HOOK_DRAW = "draw"
HOOK_LOAD = "load"
HOOK_UPDATE = "update"
HOOK_WHEELMOVED = "wheelmoved"

PHYSICS_ITERATIONS = 5
PHYSICS_TARGET_UPDATES = 45
PHYSICS_MAX_ACCUMULATOR = 2

MAX_LIGHT_INTENSITY = 255
LIGHTMAP_RESOLUTION = 512 